<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [4]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [5]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['¿Me pasas la sal, por favor?', 'espanhol'], ['Necesito comprar algunas frutas.', 'espanhol'], ["I'm learning to play the guitar.", 'inglês'], ['Hola, ¿cómo estás?', 'espanhol'], ['Me gustaría ir de vacaciones.', 'espanhol'], ['¿Puedes ayudarme con esto?', 'espanhol'], ['Quero aprender a tocar violão.', 'português'], ["I'm studying for my exams.", 'inglês'], ['Voy al parque todos los días.', 'espanhol'], ['Estou ansioso para as férias de verão.', 'português'], ['A comida estava deliciosa!', 'português'], ['Preciso fazer exercícios físicos regularmente.', 'português'], ["I'm sorry for the inconvenience.", 'inglês'], ["I'm planning a vacation.", 'inglês'], ['The weather is nice today.', 'inglês'], ['A festa começa às 20h.', 'português'], ['Você gosta de dançar?', 'português'], ['I love to read books.', 'inglês'], ['Vamos sair para jantar no sábado.', 'português'], ['Estou indo para o trabalho agora.', 'português'], ['Estoy estudiando para mis exámenes.', 'espanhol'], ['Gosto de ouvir m

O DataFrame do pandas facilita a visualização.

In [6]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0                   ¿Me pasas la sal, por favor?   espanhol
1               Necesito comprar algunas frutas.   espanhol
2               I'm learning to play the guitar.     inglês
3                             Hola, ¿cómo estás?   espanhol
4                  Me gustaría ir de vacaciones.   espanhol
..                                           ...        ...
87            Estoy emocionado por el concierto.   espanhol
88                     Quiero aprender italiano.   espanhol
89                ¿Cómo estuvo tu fin de semana?   espanhol
90  Vamos fazer um churrasco no final de semana.  português
91          O filme que assisti ontem foi ótimo.  português

[92 rows x 2 columns]

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [61]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re

def tamanhoMedioFrases(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
  return soma / len(tamanhos)


def contar_consoantes(texto):
   # retorna a quantidade de consoantes em uma frase
  padrao_consoantes = r'[bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ]' #padrão regex dos elementos que serão contados

  consoantes = re.findall(padrao_consoantes, texto)
  
  return len(consoantes)

def contar_acentuados(texto):

  #retorna o numero de caracteres com acentos gráficos
  padrao_acentos = r'[áéíóúàèìòùâêîôûãõäëïöüñçÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕÄËÏÖÜÇÑ]'#padrão regex dos elementos que serão contados
  
  acentos = re.findall(padrao_acentos, texto)

  return len(acentos)

def contar_dupla_vogal(texto):
  padrao_duplas_vogais = r'(?i)[aeiouy]{2}'

  duplas_vogais = re.findall(padrao_duplas_vogais, texto)

  return len(duplas_vogais)

def contar_termino_palavras(texto):
  padrao_terminos = r'\b\w*(?:m|an|ón|ing)\b'
  terminos = re.findall(padrao_terminos, texto, re.IGNORECASE)
  return len(terminos)

def contar_pontuacao(texto):
  padrao_pontuacao = r'\w(?:\'|¿|!)'
  pontuacao = re.findall(padrao_pontuacao, texto)

  return len(pontuacao)

def caracteristicas_ingles(texto):
  padrao_ingles = r'\w(?:\'|wh|th|ing|oo|ee|nn)'
  pd_ingles = re.findall(padrao_ingles, texto)

  return len(pd_ingles)

def caracteristicas_espanhol(texto):
  padrao_espanhol = r'\w(?:¿|el|la|ue|ie|ón|an|oy|ay)'
  pd_espanhol = re.findall(padrao_espanhol, texto)

  return len(pd_espanhol)

def caracteristicas_portugues(texto):
  padrao_portugues = r'\w(?:nh|lh|rr|ss|am)'
  pd_portugues = re.findall(padrao_portugues, texto)

  return len(pd_portugues)

def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(pattern_regex,' ',texto)
  #print(texto)
  caracteristica1=tamanhoMedioFrases(texto)
  caracteristica2=contar_consoantes(texto)
  caracteristica3=contar_acentuados(texto)
  caracteristica4=caracteristicas_ingles(texto)
  caracteristica5=caracteristicas_espanhol(texto)
  caracteristica6=caracteristicas_portugues(texto)
  # acrescente as suas funcoes no vetor padrao
  padrao = [caracteristica1, caracteristica2, caracteristica3, caracteristica4, caracteristica5,caracteristica6, frase[1] ]
  return padrao


def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

[[3.3333333333333335, 12, 0, 0, 0, 0, 'espanhol'], [7.0, 17, 0, 0, 0, 0, 'espanhol'], [3.5714285714285716, 15, 0, 1, 1, 0, 'inglês'], [4.333333333333333, 7, 2, 0, 1, 0, 'espanhol'], [4.8, 12, 1, 0, 0, 0, 'espanhol'], [5.25, 11, 0, 0, 1, 0, 'espanhol'], [5.0, 12, 1, 0, 1, 0, 'português'], [3.3333333333333335, 14, 0, 1, 0, 1, 'inglês'], [3.8333333333333335, 13, 1, 0, 2, 0, 'espanhol'], [4.428571428571429, 14, 2, 0, 0, 0, 'português'], [5.5, 10, 0, 0, 1, 0, 'português'], [8.2, 23, 2, 0, 1, 0, 'português'], [4.333333333333333, 16, 0, 0, 1, 1, 'inglês'], [3.8, 11, 0, 1, 1, 0, 'inglês'], [4.2, 12, 0, 1, 1, 0, 'inglês'], [3.4, 7, 2, 0, 0, 0, 'português'], [4.25, 9, 2, 0, 1, 0, 'português'], [3.2, 8, 0, 1, 0, 0, 'inglês'], [4.5, 15, 1, 0, 1, 1, 'português'], [4.5, 13, 0, 0, 0, 1, 'português'], [6.0, 16, 1, 0, 2, 0, 'espanhol'], [5.2, 14, 2, 0, 0, 1, 'português'], [4.75, 11, 0, 1, 1, 0, 'espanhol'], [5.857142857142857, 24, 0, 0, 1, 0, 'inglês'], [7.8, 21, 1, 0, 3, 0, 'espanhol'], [4.375, 17, 0,

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:71: SyntaxWarning: invalid escape sequence '\w'
<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:71: SyntaxWarning: invalid escape sequence '\w'
C:\Users\ana.kindinger\AppData\Local\Temp\ipykernel_15244\3816686535.py:5: SyntaxWarning: invalid escape sequence '\s'
  palavras = re.split("\s",texto)
C:\Users\ana.kindinger\AppData\Local\Temp\ipykernel_15244\3816686535.py:71: SyntaxWarning: invalid escape sequence '\w'
  pattern_regex = re.compile('[^\w+]', re.UNICODE)


0   1  2  3  4  5          6
0   3.333333  12  0  0  0  0   espanhol
1   7.000000  17  0  0  0  0   espanhol
2   3.571429  15  0  1  1  0     inglês
3   4.333333   7  2  0  1  0   espanhol
4   4.800000  12  1  0  0  0   espanhol
..       ...  .. .. .. .. ..        ...
87  5.800000  15  0  0  2  0   espanhol
88  7.333333  10  0  0  2  0   espanhol
89  3.833333  12  1  0  1  0   espanhol
90  4.500000  21  0  0  1  2  português
91  4.142857  14  1  0  1  1  português

[92 rows x 7 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [65]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)


Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [66]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


Acurácia nos dados de treinamento: 72.46%
[[16  4  3]
 [ 2 17  3]
 [ 6  1 17]]
              precision    recall  f1-score   support

    espanhol       0.67      0.70      0.68        23
      inglês       0.77      0.77      0.77        22
   português       0.74      0.71      0.72        24

    accuracy                           0.72        69
   macro avg       0.73      0.73      0.73        69
weighted avg       0.73      0.72      0.72        69

métricas mais confiáveis
[[2 4 1]
 [2 5 1]
 [2 1 5]]
              precision    recall  f1-score   support

    espanhol       0.33      0.29      0.31         7
      inglês       0.50      0.62      0.56         8
   português       0.71      0.62      0.67         8

    accuracy                           0.52        23
   macro avg       0.52      0.51      0.51        23
weighted avg       0.52      0.52      0.52        23

